- name: show return value of command module
  hosts: docker
  become: yes
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    #- debug: var=login
    - debug: msg="Logged in as user {{ login.stdout }}"
    - name: copy script to hosts
      copy:
        src: /sites/Ansible/playbooks/test.sh
        dest: /sites/test.sh
        mode: 0755
    - name: run the script
      script: test.sh
      register: result
    - debug: msg="{{ result.stdout_lines }}" 
